name: ML
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - conda[version='>=23.11.0']
  - mamba[version='>=1.5.5']
  - scikit-learn=1.3.0
  - anaconda::jupyter
  - conda-forge::scapy
  - pandas
  - pyarrow
